---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  labels:
    app: film-storage
  name: film-storage-analysis-template
spec:
  metrics:
    - name: film-storage-webmetric
      provider:
        web:
          jsonPath: '{$.status}'
          url: >-
            http://film-storage-online.<USERNAME>-canary.svc.cluster.local:8080/q/health/ready
      successCondition: result == 'UP'
