apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "service.name" . }}
spec:
  gateways:
  - {{ include "service.name" . }}
  hosts:
  - {{ include "service.name" . }}-{{ .Release.Namespace }}-istio-system.apps.{{ .Values.domain }}
  http:
  - name: primary
    route:
    - destination:
        host: {{ include "service.name" . }}.{{ .Release.Namespace }}.svc.cluster.local
        subset: stable
      weight: 100
    - destination:
        host: {{ include "service.name" . }}.{{ .Release.Namespace }}.svc.cluster.local
        subset: canary
      weight: 0